[build]
  command = "npm run build && cp -R netlify/functions/* functions/"
  publish = ".next"
  functions = "functions"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.x"
  NETLIFY_FUNCTIONS_DIR = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect for functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# These redirects are for Next.js routing
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Define functions explicitly
[functions]
  directory = "functions"
  included_files = ["functions/**"]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  functionsPort = 8888 